<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>PocketRoulette</RootNamespace>
        <AssemblyName>PocketRoulette.Fika</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Version>1.1.0</Version>
        <OutputPath>build/</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <RefsPath>../../References</RefsPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="../PocketRoulette/FikaBridge.cs" Link="FikaBridge.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../PocketRoulette/PocketRoulette.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="BepInEx">
            <HintPath>$(RefsPath)/BepInEx.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(RefsPath)/Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Comfort">
            <HintPath>$(RefsPath)/Comfort.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Fika.Core">
            <HintPath>$(RefsPath)/Fika.Core.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(RefsPath)/UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(RefsPath)/UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <PropertyGroup>
        <GamePath Condition="'$(GamePath)' == ''"></GamePath>
        <PluginPath Condition="'$(PluginPath)' == ''">$(GamePath)/BepInEx/plugins/PocketRoulette</PluginPath>
    </PropertyGroup>

    <Target Name="CopyToGame" AfterTargets="AfterBuild" Condition="'$(GamePath)' != '' And Exists('$(GamePath)/BepInEx/plugins/Fika/Fika.Core.dll')">
        <ItemGroup>
            <PluginFiles Include="$(OutputPath)$(TargetName)$(TargetExt)" />
            <PluginFiles Include="$(OutputPath)$(TargetName).pdb" Condition="Exists('$(OutputPath)$(TargetName).pdb')" />
        </ItemGroup>
        <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(PluginPath)" ContinueOnError="false" />
    </Target>
</Project>
